services:
#    cosaco_gesen.example:
#        class: Cosaco\GesenBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    gsn.loginsecurity.authentication_handler:
        class: Cosaco\GesenBundle\Handle\AuthenticationHandler
        public: false
        arguments:
            - @router
            - @session
            - @translator
            - @doctrine.orm.entity_manager
    ## Logout Handler
    gsn.logoutsecurity.logout_handler:
        class: Cosaco\GesenBundle\Handle\LogoutHandler
        public: false
        arguments:
            - @router
            - @session
            - @translator