Cosaco\GesenBundle\Entity\Dependencia:
    type: entity
    table: dependencia
    uniqueConstraints:
        cu_dependencia:
            columns:
                - nombre
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Clave primaria de la tabla'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: 'Nombre de la dependencia (Lab1, Laboratorio Media, etc)'
        prefijoHost:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: 'Prefijo sugerido para los nombres de equipos nuevos.'
            column: prefijo_host
        grupoTrabajo:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: grupo_trabajo
        fechaIngreso:
            type: datetime
            nullable: false
            comment: 'Fecha de registro de la dependencia.'
            default: CURRENT_TIMESTAMP
            column: fecha_ingreso
        habilitadoHorario:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: a
            column: habilitado_horario
        habilitadoDispositivo:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: a
            column: habilitado_dispositivo
        habilitadoMantencion:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: a
            column: habilitado_mantencion
    lifecycleCallbacks: {  }
