Cosaco\GesenBundle\Entity\Fabricante:
    type: entity
    table: fabricante
    uniqueConstraints:
        cu_fabricante:
            columns:
                - nombre_fabricante
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Clave primaria de la tabla.'
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreFabricante:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: 'Almacena marcas de fabricantes tanto de periféricos como de hardware.'
            column: nombre_fabricante
    lifecycleCallbacks: {  }
