Cosaco\GesenBundle\Entity\Software:
    type: entity
    table: software
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        categoria:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
        nombre:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        desarrollador:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        version:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        servicePack:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: service_pack
        arquitectura:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: x32
        numSerie:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: num_serie
        estado:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: a
    lifecycleCallbacks: {  }
