reservas:
    path:     /
    defaults: { _controller: "CosacoGesenBundle:Reserva:index" }

reservas_show:
    path:     /{id}/show
    defaults: { _controller: "CosacoGesenBundle:Reserva:show" }

reservas_new:
    path:     /new
    defaults: { _controller: "CosacoGesenBundle:Reserva:new" }

reservas_create:
    path:     /create
    defaults: { _controller: "CosacoGesenBundle:Reserva:create" }
    requirements: { _method: post }

reservas_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosacoGesenBundle:Reserva:edit" }

reservas_update:
    path:     /{id}/update
    defaults: { _controller: "CosacoGesenBundle:Reserva:update" }
    requirements: { _method: post|put }

reservas_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosacoGesenBundle:Reserva:delete" }
    requirements: { _method: post|delete }
